#!/usr/bin/python
from FloodLightEnvironment import FloodLightEnvironment
from FreneticEnvironment import FreneticEnvironment
from PyreticEnvironment import PyreticEnvironment
from KineticEnvironment import KineticEnvironment
from RyuEnvironment import RyuEnvironment
from MacLearningTestSuite import MacLearningTestSuite
from TestSwitchFlowrules import TestSwitchFlowrules
from TestFlowrules import TestFlowrules
from TestPackets import TestPackets
from TestPacketIn import TestPacketIn
from TestPacketsEvent import TestPacketsEvent
from JSONWriter import JSONWriter 
topoFileName = "/home/vagrant/SimpleTopo35.py"
nwTopoName = "SimpleTopo35"
testbedpath = "/home/vagrant/python/Master---Thesis/"

env = RyuEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
env.setApplication("Firewall.py")

fenv = FreneticEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
fenv.setApplication("multiswitch2.py")

'''penv = PyreticEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
penv.setApplication("ht.py")

kenv = KineticEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
kenv.setApplication("http_firewall.py")'''

flenv = FloodLightEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
flenv.setApplication("LearningSwitchFirewall.java")

flenv.additionalConfigFile(configFileName="floodlightdefault.properties",configFilePath="/home/vagrant/python/Master---Thesis/apps/floodlight/floodlightdefault.properties")
flenv.additionalConfigFile(configFileName="net.floodlightcontroller.core.module.IFloodlightModule",
                          configFilePath="/home/vagrant/python/Master---Thesis/apps/floodlight/net.floodlightcontroller.core.module.IFloodlightModule")

penv = PyreticEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
penv.setApplication("http_firewall.py")

#kenv = KineticEnvironment("/home/vagrant/python/Master---Thesis/config.ini")
#kenv.setApplication("http_firewall.py")

pnip = 1;
#env.readConfigFile()

env.setTestBedHome(testBedHomePath=testbedpath)

#sdntest1 = test_controller_packetin(testbedpath, pnip)
#sdntest1.setTopology(topoFileName, nwTopoName)

#sdntest2 = TestSwitchFlowrules(testbedpath, pnip) #periodically check switch for flow rules count
#sdntest2 = TestFlowrules(testbedpath, pnip) #flow mod messages(new rules) generated by controller
sdntest2 = TestPackets(testbedpath, pnip) #number of packets handled/generated by controller




#sdntest2 = TestPacketsEvent(testbedpath, pnip) #event duration, event type and number of pkts
sdntest2.setTopology(topoFileName, nwTopoName) 

outputFormat = JSONWriter()

suite = MacLearningTestSuite()
suite.addEnvironment(env)
suite.addEnvironment(fenv)
suite.addEnvironment(penv)
#suite.addEnvironment(kenv)
suite.addEnvironment(flenv)


#####suite.addControllerTest(sdntest1)
suite.addTestCase(sdntest2)
suite.setDataFormat(outputFormat)
suite.run()
